// Interface automatically generated by schemas-to-ts

import { ComunityBannerMember } from '../../../../components/member/interfaces/ComunityBannerMember';
import { ComunityBannerMember_Plain } from '../../../../components/member/interfaces/ComunityBannerMember';
import { ComunityBannerMember_NoRelations } from '../../../../components/member/interfaces/ComunityBannerMember';

export interface Comunity {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    ComunityMember: ComunityBannerMember;
    locale: string;
    localizations?: { data: Comunity[] };
  };
}
export interface Comunity_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  ComunityMember: ComunityBannerMember_Plain;
  locale: string;
  localizations?: Comunity_Plain[];
}

export interface Comunity_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  ComunityMember: ComunityBannerMember_NoRelations;
  locale: string;
  localizations?: Comunity[];
}

export interface Comunity_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  ComunityMember: ComunityBannerMember_Plain;
  locale: string;
  localizations?: Comunity[];
}
