// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export interface CourseComponent {
  CourseImage: { data: Media };
  CourseDate: Date;
  CourseName: string;
}
export interface CourseComponent_Plain {
  CourseImage: Media_Plain;
  CourseDate: Date;
  CourseName: string;
}

export interface CourseComponent_NoRelations {
  CourseImage: number;
  CourseDate: Date;
  CourseName: string;
}

