// Interface automatically generated by schemas-to-ts

export interface BlogItem {
  BlogTitle: string;
  BlogDescription: string;
}
export interface BlogItem_Plain {
  BlogTitle: string;
  BlogDescription: string;
}

export interface BlogItem_NoRelations {
  BlogTitle: string;
  BlogDescription: string;
}

