// Interface automatically generated by schemas-to-ts

export interface PageLink {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    pageName: string;
    pageLink: string;
    locale: string;
    localizations?: { data: PageLink[] };
  };
}
export interface PageLink_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  pageName: string;
  pageLink: string;
  locale: string;
  localizations?: PageLink_Plain[];
}

export interface PageLink_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  pageName: string;
  pageLink: string;
  locale: string;
  localizations?: PageLink[];
}

export interface PageLink_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  pageName: string;
  pageLink: string;
  locale: string;
  localizations?: PageLink[];
}
