// Interface automatically generated by schemas-to-ts

export interface About {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    aboutTitle: string;
    aboutWhoWeAre: string;
    aboutOurPrinciples: string;
    ourPrinciple1: string;
    ourPrinciple2: string;
    ourPrinciple3: string;
    ourPrinciple4: string;
    ourMision: string;
    ourVision: string;
    locale: string;
    localizations?: { data: About[] };
  };
}
export interface About_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  aboutTitle: string;
  aboutWhoWeAre: string;
  aboutOurPrinciples: string;
  ourPrinciple1: string;
  ourPrinciple2: string;
  ourPrinciple3: string;
  ourPrinciple4: string;
  ourMision: string;
  ourVision: string;
  locale: string;
  localizations?: About_Plain[];
}

export interface About_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  aboutTitle: string;
  aboutWhoWeAre: string;
  aboutOurPrinciples: string;
  ourPrinciple1: string;
  ourPrinciple2: string;
  ourPrinciple3: string;
  ourPrinciple4: string;
  ourMision: string;
  ourVision: string;
  locale: string;
  localizations?: About[];
}

export interface About_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  aboutTitle: string;
  aboutWhoWeAre: string;
  aboutOurPrinciples: string;
  ourPrinciple1: string;
  ourPrinciple2: string;
  ourPrinciple3: string;
  ourPrinciple4: string;
  ourMision: string;
  ourVision: string;
  locale: string;
  localizations?: About[];
}
