// Interface automatically generated by schemas-to-ts

import { BrandBannerItem } from './BrandBannerItem';
import { BrandBannerItem_Plain } from './BrandBannerItem';
import { BrandBannerItem_NoRelations } from './BrandBannerItem';

export interface BrandBanner {
  BrandBannerItem: BrandBannerItem[];
}
export interface BrandBanner_Plain {
  BrandBannerItem: BrandBannerItem_Plain[];
}

export interface BrandBanner_NoRelations {
  BrandBannerItem: BrandBannerItem_NoRelations[];
}

