// Interface automatically generated by schemas-to-ts

export interface BrandBannerItem {
  BranBannerItemImgLink: string;
  BrandBannerItemImgAlt: string;
}
export interface BrandBannerItem_Plain {
  BranBannerItemImgLink: string;
  BrandBannerItemImgAlt: string;
}

export interface BrandBannerItem_NoRelations {
  BranBannerItemImgLink: string;
  BrandBannerItemImgAlt: string;
}

