// Interface automatically generated by schemas-to-ts

export interface Post {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    postName: string;
    postDescription: string;
    locale: string;
    localizations?: { data: Post[] };
  };
}
export interface Post_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  postName: string;
  postDescription: string;
  locale: string;
  localizations?: Post_Plain[];
}

export interface Post_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  postName: string;
  postDescription: string;
  locale: string;
  localizations?: Post[];
}

export interface Post_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  postName: string;
  postDescription: string;
  locale: string;
  localizations?: Post[];
}
