// Interface automatically generated by schemas-to-ts

export interface SocialNetwork {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    socialNetworkName: string;
    socialNetworkLink: string;
    locale: string;
    localizations?: { data: SocialNetwork[] };
  };
}
export interface SocialNetwork_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  socialNetworkName: string;
  socialNetworkLink: string;
  locale: string;
  localizations?: SocialNetwork_Plain[];
}

export interface SocialNetwork_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  socialNetworkName: string;
  socialNetworkLink: string;
  locale: string;
  localizations?: SocialNetwork[];
}

export interface SocialNetwork_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  socialNetworkName: string;
  socialNetworkLink: string;
  locale: string;
  localizations?: SocialNetwork[];
}
