// Interface automatically generated by schemas-to-ts

export interface Footer {
  FooterListName: string;
  FooterListLink: string;
}
export interface Footer_Plain {
  FooterListName: string;
  FooterListLink: string;
}

export interface Footer_NoRelations {
  FooterListName: string;
  FooterListLink: string;
}

