// Interface automatically generated by schemas-to-ts

export interface BannerHomeSection {
  BannerHomeTitle: string;
}
export interface BannerHomeSection_Plain {
  BannerHomeTitle: string;
}

export interface BannerHomeSection_NoRelations {
  BannerHomeTitle: string;
}

