// Interface automatically generated by schemas-to-ts

import { ContactHomeSectionFormItem } from './ContactHomeSectionFormItem';
import { ContactHomeSectionFormItem_Plain } from './ContactHomeSectionFormItem';
import { ContactHomeSectionFormItem_NoRelations } from './ContactHomeSectionFormItem';

export interface ContactHomeSectionForm {
  ContactHomeSectionFormItem: ContactHomeSectionFormItem[];
}
export interface ContactHomeSectionForm_Plain {
  ContactHomeSectionFormItem: ContactHomeSectionFormItem_Plain[];
}

export interface ContactHomeSectionForm_NoRelations {
  ContactHomeSectionFormItem: ContactHomeSectionFormItem_NoRelations[];
}

