// Interface automatically generated by schemas-to-ts

export interface ContactHomeSectionFormItem {
  ContactFormInputName: string;
  ContactFormInputLabel: string;
}
export interface ContactHomeSectionFormItem_Plain {
  ContactFormInputName: string;
  ContactFormInputLabel: string;
}

export interface ContactHomeSectionFormItem_NoRelations {
  ContactFormInputName: string;
  ContactFormInputLabel: string;
}

