// Interface automatically generated by schemas-to-ts

import { ContactHomeSectionForm } from './ContactHomeSectionForm';
import { ContactHomeSectionForm_Plain } from './ContactHomeSectionForm';
import { ContactHomeSectionForm_NoRelations } from './ContactHomeSectionForm';

export interface ContactHomeSection {
  ContactHomeSectionTitle: string;
  ContactHomeSectionDescription: string;
  ContactHomeSectionPhoneNumber: string;
  ContactHomeSectionEmail: string;
  ContactHomeSectionForm: ContactHomeSectionForm;
}
export interface ContactHomeSection_Plain {
  ContactHomeSectionTitle: string;
  ContactHomeSectionDescription: string;
  ContactHomeSectionPhoneNumber: string;
  ContactHomeSectionEmail: string;
  ContactHomeSectionForm: ContactHomeSectionForm_Plain;
}

export interface ContactHomeSection_NoRelations {
  ContactHomeSectionTitle: string;
  ContactHomeSectionDescription: string;
  ContactHomeSectionPhoneNumber: string;
  ContactHomeSectionEmail: string;
  ContactHomeSectionForm: ContactHomeSectionForm_NoRelations;
}

