// Interface automatically generated by schemas-to-ts

export interface CoursesHomeSection {
  CourseHomeSectionTitle: string;
  CourseHomeSectionDescription: string;
}
export interface CoursesHomeSection_Plain {
  CourseHomeSectionTitle: string;
  CourseHomeSectionDescription: string;
}

export interface CoursesHomeSection_NoRelations {
  CourseHomeSectionTitle: string;
  CourseHomeSectionDescription: string;
}

