// Interface automatically generated by schemas-to-ts

export interface MemberHomeSection {
  MemberHomeSectionTitle: string;
  MemberHomeSectionDescription: string;
}
export interface MemberHomeSection_Plain {
  MemberHomeSectionTitle: string;
  MemberHomeSectionDescription: string;
}

export interface MemberHomeSection_NoRelations {
  MemberHomeSectionTitle: string;
  MemberHomeSectionDescription: string;
}

