// Interface automatically generated by schemas-to-ts

export interface SpecialtyHomeSection {
  SpecialtyHomeSectionTitle: string;
  SpecialtyHomeSectionDescription: string;
}
export interface SpecialtyHomeSection_Plain {
  SpecialtyHomeSectionTitle: string;
  SpecialtyHomeSectionDescription: string;
}

export interface SpecialtyHomeSection_NoRelations {
  SpecialtyHomeSectionTitle: string;
  SpecialtyHomeSectionDescription: string;
}

