// Interface automatically generated by schemas-to-ts

export interface UpcomingEventsSection {
  UpcomingEventHomeSectionTitle: string;
  UpcomingEventHomeSectionDescription: string;
}
export interface UpcomingEventsSection_Plain {
  UpcomingEventHomeSectionTitle: string;
  UpcomingEventHomeSectionDescription: string;
}

export interface UpcomingEventsSection_NoRelations {
  UpcomingEventHomeSectionTitle: string;
  UpcomingEventHomeSectionDescription: string;
}

