// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Eventt {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    eventName: string;
    eventDate: Date;
    eventIsInPerson: boolean;
    eventDeadline: Date;
    eventRequirements: any;
    eventDescription: string;
    eventWhatToSubmit: any;
    eventPrizes1: any;
    eventPrizes2: any;
    eventPrizes3: any;
    eventPrizes4?: any;
    eventPrizes5?: any;
    eventPrizes6?: any;
    eventJudgingCriteria: any;
    eventImage: { data: Media };
    locale: string;
    localizations?: { data: Eventt[] };
  };
}
export interface Eventt_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  eventName: string;
  eventDate: Date;
  eventIsInPerson: boolean;
  eventDeadline: Date;
  eventRequirements: any;
  eventDescription: string;
  eventWhatToSubmit: any;
  eventPrizes1: any;
  eventPrizes2: any;
  eventPrizes3: any;
  eventPrizes4?: any;
  eventPrizes5?: any;
  eventPrizes6?: any;
  eventJudgingCriteria: any;
  eventImage: Media_Plain;
  locale: string;
  localizations?: Eventt_Plain[];
}

export interface Eventt_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  eventName: string;
  eventDate: Date;
  eventIsInPerson: boolean;
  eventDeadline: Date;
  eventRequirements: any;
  eventDescription: string;
  eventWhatToSubmit: any;
  eventPrizes1: any;
  eventPrizes2: any;
  eventPrizes3: any;
  eventPrizes4?: any;
  eventPrizes5?: any;
  eventPrizes6?: any;
  eventJudgingCriteria: any;
  eventImage: number;
  locale: string;
  localizations?: Eventt[];
}

export interface Eventt_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  eventName: string;
  eventDate: Date;
  eventIsInPerson: boolean;
  eventDeadline: Date;
  eventRequirements: any;
  eventDescription: string;
  eventWhatToSubmit: any;
  eventPrizes1: any;
  eventPrizes2: any;
  eventPrizes3: any;
  eventPrizes4?: any;
  eventPrizes5?: any;
  eventPrizes6?: any;
  eventJudgingCriteria: any;
  eventImage: AdminPanelRelationPropertyModification<Media_Plain>;
  locale: string;
  localizations?: Eventt[];
}
