// Interface automatically generated by schemas-to-ts

import { EventBanner } from '../../../../components/event/interfaces/EventBanner';
import { EventTrendSection } from '../../../../components/event/interfaces/EventTrendSection';
import { EventIncomingSection } from '../../../../components/event/interfaces/EventIncomingSection';
import { EventPastSection } from '../../../../components/event/interfaces/EventPastSection';
import { EventBanner_Plain } from '../../../../components/event/interfaces/EventBanner';
import { EventTrendSection_Plain } from '../../../../components/event/interfaces/EventTrendSection';
import { EventIncomingSection_Plain } from '../../../../components/event/interfaces/EventIncomingSection';
import { EventPastSection_Plain } from '../../../../components/event/interfaces/EventPastSection';
import { EventBanner_NoRelations } from '../../../../components/event/interfaces/EventBanner';
import { EventTrendSection_NoRelations } from '../../../../components/event/interfaces/EventTrendSection';
import { EventIncomingSection_NoRelations } from '../../../../components/event/interfaces/EventIncomingSection';
import { EventPastSection_NoRelations } from '../../../../components/event/interfaces/EventPastSection';

export interface Event {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    EventBanner: EventBanner;
    EventTrendSection: EventTrendSection;
    EventIncoming: EventIncomingSection;
    EventPast: EventPastSection;
    locale: string;
    localizations?: { data: Event[] };
  };
}
export interface Event_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  EventBanner: EventBanner_Plain;
  EventTrendSection: EventTrendSection_Plain;
  EventIncoming: EventIncomingSection_Plain;
  EventPast: EventPastSection_Plain;
  locale: string;
  localizations?: Event_Plain[];
}

export interface Event_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  EventBanner: EventBanner_NoRelations;
  EventTrendSection: EventTrendSection_NoRelations;
  EventIncoming: EventIncomingSection_NoRelations;
  EventPast: EventPastSection_NoRelations;
  locale: string;
  localizations?: Event[];
}

export interface Event_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  EventBanner: EventBanner_Plain;
  EventTrendSection: EventTrendSection_Plain;
  EventIncoming: EventIncomingSection_Plain;
  EventPast: EventPastSection_Plain;
  locale: string;
  localizations?: Event[];
}
