// Interface automatically generated by schemas-to-ts

import { BannerHomeSection } from '../../../../components/home/interfaces/BannerHomeSection';
import { SpecialtyHomeSection } from '../../../../components/home/interfaces/SpecialtyHomeSection';
import { CoursesHomeSection } from '../../../../components/home/interfaces/CoursesHomeSection';
import { MemberHomeSection } from '../../../../components/home/interfaces/MemberHomeSection';
import { UpcomingEventsSection } from '../../../../components/home/interfaces/UpcomingEventsSection';
import { ContactHomeSection } from '../../../../components/home/interfaces/ContactHomeSection';
import { FooterHomeSection } from '../../../../components/home/interfaces/FooterHomeSection';
import { BannerHomeSection_Plain } from '../../../../components/home/interfaces/BannerHomeSection';
import { SpecialtyHomeSection_Plain } from '../../../../components/home/interfaces/SpecialtyHomeSection';
import { CoursesHomeSection_Plain } from '../../../../components/home/interfaces/CoursesHomeSection';
import { MemberHomeSection_Plain } from '../../../../components/home/interfaces/MemberHomeSection';
import { UpcomingEventsSection_Plain } from '../../../../components/home/interfaces/UpcomingEventsSection';
import { ContactHomeSection_Plain } from '../../../../components/home/interfaces/ContactHomeSection';
import { FooterHomeSection_Plain } from '../../../../components/home/interfaces/FooterHomeSection';
import { BannerHomeSection_NoRelations } from '../../../../components/home/interfaces/BannerHomeSection';
import { SpecialtyHomeSection_NoRelations } from '../../../../components/home/interfaces/SpecialtyHomeSection';
import { CoursesHomeSection_NoRelations } from '../../../../components/home/interfaces/CoursesHomeSection';
import { MemberHomeSection_NoRelations } from '../../../../components/home/interfaces/MemberHomeSection';
import { UpcomingEventsSection_NoRelations } from '../../../../components/home/interfaces/UpcomingEventsSection';
import { ContactHomeSection_NoRelations } from '../../../../components/home/interfaces/ContactHomeSection';
import { FooterHomeSection_NoRelations } from '../../../../components/home/interfaces/FooterHomeSection';

export interface Home {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    BannerHomeSection: BannerHomeSection;
    SpecialtyHomeSection: SpecialtyHomeSection;
    CourseHomeSection: CoursesHomeSection;
    MemberHomeSection: MemberHomeSection;
    UpcomingEventHomeSection: UpcomingEventsSection;
    ContactHomeSection: ContactHomeSection;
    FotterHomeSection: FooterHomeSection;
    locale: string;
    localizations?: { data: Home[] };
  };
}
export interface Home_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  BannerHomeSection: BannerHomeSection_Plain;
  SpecialtyHomeSection: SpecialtyHomeSection_Plain;
  CourseHomeSection: CoursesHomeSection_Plain;
  MemberHomeSection: MemberHomeSection_Plain;
  UpcomingEventHomeSection: UpcomingEventsSection_Plain;
  ContactHomeSection: ContactHomeSection_Plain;
  FotterHomeSection: FooterHomeSection_Plain;
  locale: string;
  localizations?: Home_Plain[];
}

export interface Home_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  BannerHomeSection: BannerHomeSection_NoRelations;
  SpecialtyHomeSection: SpecialtyHomeSection_NoRelations;
  CourseHomeSection: CoursesHomeSection_NoRelations;
  MemberHomeSection: MemberHomeSection_NoRelations;
  UpcomingEventHomeSection: UpcomingEventsSection_NoRelations;
  ContactHomeSection: ContactHomeSection_NoRelations;
  FotterHomeSection: FooterHomeSection_NoRelations;
  locale: string;
  localizations?: Home[];
}

export interface Home_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  BannerHomeSection: BannerHomeSection_Plain;
  SpecialtyHomeSection: SpecialtyHomeSection_Plain;
  CourseHomeSection: CoursesHomeSection_Plain;
  MemberHomeSection: MemberHomeSection_Plain;
  UpcomingEventHomeSection: UpcomingEventsSection_Plain;
  ContactHomeSection: ContactHomeSection_Plain;
  FotterHomeSection: FooterHomeSection_Plain;
  locale: string;
  localizations?: Home[];
}
