// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Course } from '../../../course/content-types/course/course';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Course_Plain } from '../../../course/content-types/course/course';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Specialtie {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    specialtiesName: string;
    specialtiesDescription: string;
    specialtieLogo: string;
    specialtieImage: { data: Media };
    courses: { data: Course[] };
    locale: string;
    localizations?: { data: Specialtie[] };
  };
}
export interface Specialtie_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  specialtiesName: string;
  specialtiesDescription: string;
  specialtieLogo: string;
  specialtieImage: Media_Plain;
  courses: Course_Plain[];
  locale: string;
  localizations?: Specialtie_Plain[];
}

export interface Specialtie_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  specialtiesName: string;
  specialtiesDescription: string;
  specialtieLogo: string;
  specialtieImage: number;
  courses: number[];
  locale: string;
  localizations?: Specialtie[];
}

export interface Specialtie_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  specialtiesName: string;
  specialtiesDescription: string;
  specialtieLogo: string;
  specialtieImage: AdminPanelRelationPropertyModification<Media_Plain>;
  courses: AdminPanelRelationPropertyModification<Course_Plain>;
  locale: string;
  localizations?: Specialtie[];
}
