// Interface automatically generated by schemas-to-ts

export interface ComunityBannerMember {
  ComunityBannerTitle: string;
  ComunityBannerDescription: string;
  comunityDiscordLink: string;
}
export interface ComunityBannerMember_Plain {
  ComunityBannerTitle: string;
  ComunityBannerDescription: string;
  comunityDiscordLink: string;
}

export interface ComunityBannerMember_NoRelations {
  ComunityBannerTitle: string;
  ComunityBannerDescription: string;
  comunityDiscordLink: string;
}

