// Interface automatically generated by schemas-to-ts

import { MemberComponent } from './MemberComponent';
import { MemberComponent_Plain } from './MemberComponent';
import { MemberComponent_NoRelations } from './MemberComponent';

export interface ComunityMembersGroup {
  ComunityMember: MemberComponent[];
}
export interface ComunityMembersGroup_Plain {
  ComunityMember: MemberComponent_Plain[];
}

export interface ComunityMembersGroup_NoRelations {
  ComunityMember: MemberComponent_NoRelations[];
}

