// Interface automatically generated by schemas-to-ts

export interface MemberComponent {
  MemberSpecialty: string;
  MemberName: string;
  MemberLocation: string;
  MemberCicle: number;
  MemberLinkedIn: string;
  MemberGithubLink: string;
}
export interface MemberComponent_Plain {
  MemberSpecialty: string;
  MemberName: string;
  MemberLocation: string;
  MemberCicle: number;
  MemberLinkedIn: string;
  MemberGithubLink: string;
}

export interface MemberComponent_NoRelations {
  MemberSpecialty: string;
  MemberName: string;
  MemberLocation: string;
  MemberCicle: number;
  MemberLinkedIn: string;
  MemberGithubLink: string;
}

