// Interface automatically generated by schemas-to-ts

export interface EventIncomingSection {
  EventIncomingSectionTitle: string;
  EventIncomingSectionDescription: string;
}
export interface EventIncomingSection_Plain {
  EventIncomingSectionTitle: string;
  EventIncomingSectionDescription: string;
}

export interface EventIncomingSection_NoRelations {
  EventIncomingSectionTitle: string;
  EventIncomingSectionDescription: string;
}

