// Interface automatically generated by schemas-to-ts

export interface EventsList {
  EventName: string;
  EventLocation?: string;
  EventDate?: Date;
  EventIsPresencial: boolean;
  EventDescription: string;
  EventLink: string;
}
export interface EventsList_Plain {
  EventName: string;
  EventLocation?: string;
  EventDate?: Date;
  EventIsPresencial: boolean;
  EventDescription: string;
  EventLink: string;
}

export interface EventsList_NoRelations {
  EventName: string;
  EventLocation?: string;
  EventDate?: Date;
  EventIsPresencial: boolean;
  EventDescription: string;
  EventLink: string;
}

