// Interface automatically generated by schemas-to-ts

export interface EventBanner {
  EventMainTitle: string;
  EventMainDescription: string;
}
export interface EventBanner_Plain {
  EventMainTitle: string;
  EventMainDescription: string;
}

export interface EventBanner_NoRelations {
  EventMainTitle: string;
  EventMainDescription: string;
}

