// Interface automatically generated by schemas-to-ts

export interface EventPastSection {
  EventPastSectionTitle: string;
  EventPastSectionDescription: string;
}
export interface EventPastSection_Plain {
  EventPastSectionTitle: string;
  EventPastSectionDescription: string;
}

export interface EventPastSection_NoRelations {
  EventPastSectionTitle: string;
  EventPastSectionDescription: string;
}

