// Interface automatically generated by schemas-to-ts

export interface EventTrendSection {
  EventTrendTitle: string;
}
export interface EventTrendSection_Plain {
  EventTrendTitle: string;
}

export interface EventTrendSection_NoRelations {
  EventTrendTitle: string;
}

