// Interface automatically generated by schemas-to-ts

export interface SpecialtyComponent {
  SpecialtyComponentTitle: string;
  SpecialtyComponentDescription: string;
  SpecialtyComponentLink: string;
}
export interface SpecialtyComponent_Plain {
  SpecialtyComponentTitle: string;
  SpecialtyComponentDescription: string;
  SpecialtyComponentLink: string;
}

export interface SpecialtyComponent_NoRelations {
  SpecialtyComponentTitle: string;
  SpecialtyComponentDescription: string;
  SpecialtyComponentLink: string;
}

